config/routes.rb
Rails.application.routes.draw do
  get 'requests/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'full_calendar#index'

  namespace :api do
    defaults format: :json do
      resources :schedules
      resources :courses
    end
  end

  resources :systems
  resources :courses
  resources :resources
  resources :entries do
    collection do
      # get 'new_from_calendar'
    end
  end
  resources :customers
  resources 'full_calendar'
end

app/models/customer.rb
class Customer < ApplicationRecord
  include CustomerDecorator

  has_many :entry

  enumerize :gender, in: {
    male:     1,
    female:   2,
    other:    3
  }

  enumerize :status, in: {
    initial: 0,
    member: 1,
    cancel: 2
  }

  def full_name
    "#{last_name} #{first_name}"
  end

  def full_tell
    "#{tel1}-#{tel2}-#{tel3}"
  end

  def full_zip
    "#{zip1}-#{zip2}"
  end

  def full_address
    "#{addr1} #{addr2} #{addr3}"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  def index
    @start_time = params[:start] ? Date.parse(params[:start]) : sys_date.to_s
    @end_time = params[:end] ? Date.parse(params[:end]) : sys_date.to_s

    @customers = Customer.all
    respond_to do |format|
      format.html
      format.json { render json: @customers.to_json }
      format.js
    end
  end

  # GET /customers/1
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /customers/1
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /customers/1
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def customer_params
      params.require(:customer).permit(model_class.param_names)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.slim
= simple_form_for(@customer, html: { class: 'form-horizontal' }) do |f|
  - ar_errors(@customer)

  .form-inputs
    = f.input :status
    = f.input :last_name
    = f.input :first_name
    = f.input :last_kana
    = f.input :first_kana
    = f.input :gender
    = f.input :birth
    = f.input :zip1
    = f.input :zip2
    = f.input :addr1
    = f.input :addr2
    = f.input :addr3
    = f.input :tel1
    = f.input :tel2
    = f.input :tel3
    = f.input :email
    = f.input :note

  .form-actions
    .col-sm-offset-2
      = f.button :submit, class: 'btn btn-primary'

app/views/customers/_search.html.slim
.modal-content
  .modal-header
    = link_to '新規顧客', new_customer_path, remote: true, id: :new_customer, class: 'btn btn-primary'
  .modal-body
    .table-responsive
        table.table.table-striped.table-bordered.table-hover.datatable
          thead
            tr
              th
                | status
              th
                | Name
              th
                | Gender
              th
                | Tell
              th
                | Zip
              th
                | Address
          tbody
            - @customers.each do | customer |
              tr data-href="#{new_entry_path(format: :js, customer_id: customer.id, start_time: @start_time, end_time: @end_time)}"
                td
                  = customer.status_text
                td
                  = customer.name
                td
                  = customer.gender
                td
                  = customer.full_tell
                td
                  = customer.full_zip
                td
                  = customer.full_address
  .modal-footer

app/views/customers/edit.html.slim
.page-header
  = link_to customers_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @customer, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | customer

= render 'form'

app/views/customers/index.html.slim
.page-header
  = link_to new_customer_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Customer
  h1
    | Listing customers

.table-responsive
  table.table.table-striped.table-bordered.table-hover.datatable
    thead
      tr
        th
          | Id
        th
          | status
        th
          | Last name
        th
          | First name
        th
          | Last kana
        th
          | First kana
        th
          | Gender
        th
          | Birth
        th
          | Zip1
        th
          | Zip2
        th
          | Addr1
        th
          | Addr2
        th
          | Addr3
        th
          | Tel1
        th
          | Tel2
        th
          | Tel3
        th
          | Email
        th
          | Note
        th
          | Deleted at
        th
          | Created at
        th
          | Updated at
        th
        th
        th
    tbody
      - @customers.each do | customer |
        tr
          td
            = link_to "#{customer.id}", edit_customer_path(customer) 
          td
            = customer.status_text
          td
            = customer.last_name
          td
            = customer.first_name
          td
            = customer.last_kana
          td
            = customer.first_kana
          td
            = customer.gender
          td
            = customer.birth
          td
            = customer.zip1
          td
            = customer.zip2
          td
            = customer.addr1
          td
            = customer.addr2
          td
            = customer.addr3
          td
            = customer.tel1
          td
            = customer.tel2
          td
            = customer.tel3
          td
            = customer.email
          td
            = customer.note
          td
            = customer.deleted_at
          td
            = customer.created_at
          td
            = customer.updated_at
          td
            = link_to 'Show', customer
          td
            = link_to 'Edit', edit_customer_path(customer) 
          td
            = link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } 

div#calendar

app/views/customers/new.html.slim
.page-header
  = link_to customers_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | customer

= render 'form'

app/views/customers/show.html.slim
.page-header
  = link_to customers_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_customer_path(@customer), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show customer
dl.dl-horizontal
  dt
    | Id:
  dd
    = @customer.id
  dt
    | Last name:
  dd
    = @customer.last_name
  dt
    | First name:
  dd
    = @customer.first_name
  dt
    | Last kana:
  dd
    = @customer.last_kana
  dt
    | First kana:
  dd
    = @customer.first_kana
  dt
    | Gender:
  dd
    = @customer.gender
  dt
    | Birth:
  dd
    = @customer.birth
  dt
    | Zip1:
  dd
    = @customer.zip1
  dt
    | Zip2:
  dd
    = @customer.zip2
  dt
    | Addr1:
  dd
    = @customer.addr1
  dt
    | Addr2:
  dd
    = @customer.addr2
  dt
    | Addr3:
  dd
    = @customer.addr3
  dt
    | Tel1:
  dd
    = @customer.tel1
  dt
    | Tel2:
  dd
    = @customer.tel2
  dt
    | Tel3:
  dd
    = @customer.tel3
  dt
    | Email:
  dd
    = @customer.email
  dt
    | Note:
  dd
    = @customer.note
  dt
    | Deleted at:
  dd
    = @customer.deleted_at
  dt
    | Created at:
  dd
    = @customer.created_at
  dt
    | Updated at:
  dd
    = @customer.updated_at