config/routes.rb
Rails.application.routes.draw do
  get 'requests/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'full_calendar#index'

  namespace :api do
    defaults format: :json do
      resources :schedules
      resources :courses
    end
  end

  resources :systems
  resources :courses
  resources :resources
  resources :entries do
    collection do
      # get 'new_from_calendar'
    end
  end
  resources :customers
  resources 'full_calendar'
end

app/views/resources/_form.html.slim
= simple_form_for(@resource, html: { class: 'form-horizontal' }) do |f|
  - ar_errors(@resource)

  .form-inputs
    = f.input :name
    = f.input :color
    = f.input :note

  .form-actions
    .col-sm-offset-2
      = f.button :submit, class: 'btn btn-primary'

app/views/resources/edit.html.slim
.page-header
  = link_to resources_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @resource, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | resource

= render 'form'

app/views/resources/index.html.slim
.page-header
  = link_to new_resource_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Resource
  h1
    | Listing resources

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Id
        th
          | Name
        th
          | Color
        th
          | Note
        th
          | Deleted at
        th
          | Created at
        th
          | Updated at
        th
        th
        th
    tbody
      - @resources.each do | resource |
        tr
          td
            = resource.id
          td
            = resource.name
          td
            = resource.color
          td
            = resource.note
          td
            = resource.deleted_at
          td
            = resource.created_at
          td
            = resource.updated_at
          td
            = link_to 'Show', resource
          td
            = link_to 'Edit', edit_resource_path(resource) 
          td
            = link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/resources/new.html.slim
.page-header
  = link_to resources_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | resource

= render 'form'

app/views/resources/show.html.slim
.page-header
  = link_to resources_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_resource_path(@resource), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show resource
dl.dl-horizontal
  dt
    | Id:
  dd
    = @resource.id
  dt
    | Name:
  dd
    = @resource.name
  dt
    | Color:
  dd
    = @resource.color
  dt
    | Note:
  dd
    = @resource.note
  dt
    | Deleted at:
  dd
    = @resource.deleted_at
  dt
    | Created at:
  dd
    = @resource.created_at
  dt
    | Updated at:
  dd
    = @resource.updated_at