config/routes.rb
Rails.application.routes.draw do
  get 'requests/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'full_calendar#index'

  namespace :api do
    defaults format: :json do
      resources :schedules
      resources :courses
    end
  end

  resources :systems
  resources :courses
  resources :resources
  resources :entries do
    collection do
      # get 'new_from_calendar'
    end
  end
  resources :customers
  resources 'full_calendar'
end

app/models/system.rb
class System < ApplicationRecord
  enumerize :entry_unit, in: {
    day:  1,
    hour: 2
  }
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  before_action :set_system, only: [:show, :edit, :update, :destroy]

  # GET /systems
  def index
    @systems = System.all
  end

  # GET /systems/1
  def show
  end

  # GET /systems/new
  def new
    @system = System.new
  end

  # GET /systems/1/edit
  def edit
  end

  # POST /systems
  def create
    @system = System.new(system_params)

    if @system.save
      redirect_to @system, notice: 'System was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /systems/1
  def update
    if @system.update(system_params)
      redirect_to @system, notice: 'System was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /systems/1
  def destroy
    @system.destroy
    redirect_to systems_url, notice: 'System was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system
      @system = System.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def system_params
      params.require(:system).permit(model_class.param_names)
    end
end

app/views/systems/_form.html.slim
= simple_form_for(@system, html: { class: 'form-horizontal' }) do |f|
  - ar_errors(@system)

  .form-inputs
    = f.input :name
    = f.input :entry_unit
    = f.input :site_url, as: :url
    = f.input :member_management_flag

  .form-actions
    .col-sm-offset-2
      = f.button :submit, class: 'btn btn-primary'

app/views/systems/edit.html.slim
.page-header
  = link_to systems_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @system, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | system

= render 'form'

app/views/systems/index.html.slim
.page-header
  = link_to new_system_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New System
  h1
    | Listing systems

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Id
        th
          | Name
        th
          | Entry unit
        th
          | Member management flag
        th
          | Homepage url
        th
          | Deleted at
        th
          | Created at
        th
          | Updated at
        th
        th
        th
    tbody
      - @systems.each do | system |
        tr
          td
            = system.id
          td
            = system.name
          td
            = system.entry_unit
          td
            = system.member_management_flag
          td
            = link_to system.site_url, system.site_url, target: '_new'
          td
            = system.deleted_at
          td
            = system.created_at
          td
            = system.updated_at
          td
            = link_to 'Show', system
          td
            = link_to 'Edit', edit_system_path(system) 
          td
            = link_to 'Destroy', system, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/systems/new.html.slim
.page-header
  = link_to systems_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | system

= render 'form'

app/views/systems/show.html.slim
.page-header
  = link_to systems_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_system_path(@system), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show system
dl.dl-horizontal
  dt
    | Id:
  dd
    = @system.id
  dt
    | Name:
  dd
    = @system.name
  dt
    | Entry unit:
  dd
    = @system.entry_unit
  dt
    | Member management flag:
  dd
    = @system.member_management_flag
  dt
    | Deleted at:
  dd
    = @system.deleted_at
  dt
    | Created at:
  dd
    = @system.created_at
  dt
    | Updated at:
  dd
    = @system.updated_at